### ISSUE TITLE
Error 'An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id AuditManagerBlogStack does not exist'

### ISSUE THREAD

**Issue by takakuni-classmethod** [aws-samples/enterprise-controls-catalog-via-aws-audit-manager#1]
# as is:
When I follow the [Deployment](https://github.com/aws-samples/enterprise-controls-catalog-via-aws-audit-manager#deployment), I get the error in the title.

---------------------------------------

# to be:
---------------------------------------
The stack name: AuditManagerBlogStack must have been created before executing deploy.sh.

In line 12, an error occurs because we are referring to an uncreated stack.

[relevant line](https://github.com/aws-samples/enterprise-controls-catalog-via-aws-audit-manager/blob/main/deploy.sh#L12)

```
BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name AuditManagerBlogStack --output json | jq -r '.Stacks[].Outputs[] | select ( .OutputKey | contains("bucket") ) | .OutputValue')
```

# environment: 
------------------------------------------------------
macOS Big Sur 11.6 (Apple M1)
node.js v16.3.0
aws cli 2.4.10
aws cdk 2.8.0
jq jq-1.6
git version 2.32.0 (Apple Git-132)

**Comment by deenadat** [comment]
Thanks for reaching out.  Looks like AuditManagerBlogStack is yet to be built.

I have updated the CDK to V2 and committed the code. Kindly clone the latest code and try again.

Kindly ensure following pre-requisite are configured before running ./deploy.sh
1. AWS Audit Manager is enabled in the region deployed
2. Set your AWS Credentials to deploy the stack
export AWS_ACCESS_KEY_ID=<<Access Key ID>>
export AWS_SECRET_ACCESS_KEY=<<Secret Access key>>
export AWS_REGION = <<ap-southeast-2>>

**Comment by takakuni-classmethod** [comment]
> Thanks for reaching out. Looks like AuditManagerBlogStack is yet to be built.
> 
> I have updated the CDK to V2 and committed the code. Kindly clone the latest code and try again.
> 
> Kindly ensure following pre-requisite are configured before running ./deploy.sh
> 
> 1. AWS Audit Manager is enabled in the region deployed
> 2. Set your AWS Credentials to deploy the stack
>    export AWS_ACCESS_KEY_ID=<>
>    export AWS_SECRET_ACCESS_KEY=<>
>    export AWS_REGION = <>

Thanks for the reply, and thanks for the update to CDK v2.

I think I didn't get around the environment variable for the access key, so it didn't go through...

I was able to create it successfully with the configuration values you shared.

Thank you very much.
